version: '3.7'

services:
  webf1project:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-#_+o@*=gs$xo5h8n59f+j@&tuq%2c&rdq=e3(r1-g$a0tvj(s*
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - dbf1project

  dbf1project:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
