# Generated by Django 5.2.4 on 2025-07-06 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paddock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('comparison_type', models.CharField(choices=[('scatter_laps', 'Race Laps'), ('throttle_brake', 'Throttle vs Brake'), ('speed_distribution', 'Speed Bins')], max_length=50)),
                ('plot_base64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_driver1', to='paddock.driver')),
                ('driver2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_driver2', to='paddock.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paddock.race')),
            ],
            options={
                'unique_together': {('season', 'race', 'driver1', 'driver2', 'comparison_type')},
            },
        ),
    ]
