# Generated by Django 5.2.4 on 2025-07-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaddockImporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.BooleanField(default=False)),
            ],
        ),
    ]
